extends:
- stylelint-config-standard
- stylelint-config-standard-scss
- stylelint-config-idiomatic-order
rules:
  alpha-value-notation: percentage
  color-function-notation: legacy
  property-no-vendor-prefix:
  - true
  - ignoreProperties:
    - "/^mask-/"

